### PR TITLE
Check we have permission to trace, and fix file permissions.

### LINKED ISSUE #7: Does not need to run as root.
If `/proc/sys/kernel/perf_event_paranoid` contains `-1`, then the tracer can run as an unprivileged user.

### PR DESCRIPTION
**Pull request by vext01**
This change:

 * Checks we have permission to trace.
 * Ensures the `ptt` and `map` files are created with appropriate permissions.

Looks good?

Fixes #7

### CODE REVIEW

**Comment by vext01** [comment]
There's travis sorted.

File: src/errors.rs [hunk 1]
```diff
@@ -25,15 +29,32 @@ impl From<ffi::NulError> for TraceMeError {
...
+    }
+}
+
 impl Display for TraceMeError {
     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
         match self {
             &TraceMeError::FFIIntoString(ref e) => write!(f, "{}", e),
             &TraceMeError::FFINul(ref e) => write!(f, "{}", e),
+            &TraceMeError::IO(ref e) => write!(f, "{}", e),
+            &TraceMeError::NumParseInt(ref e) => write!(f, "{}", e),
```
Comment (ltratt) [inline src/errors.rs]: For all of these cases, you might want to merge them using `|`?

File: src/lib.rs [hunk 2]
```diff
@@ -42,10 +42,14 @@ extern crate libc;
...
 
-use libc::{pid_t, c_char, c_void, getpid, size_t, c_int};
+use libc::{pid_t, c_char, c_void, getpid, size_t, c_int, geteuid};
 use std::ffi::CString;
 use std::path::PathBuf;
 use errors::TraceMeError;
+use std::fs::File;
+use std::io::Read;
+
+const PERF_PERMS_PATH: &'static str = "/proc/sys/kernel/perf_event_paranoid";
```
Comment (ltratt) [inline src/lib.rs]: I think this should be guarded with a `#[cfg(Linux)]` or whatever it is. At some point we'll want this run on non-Linux, so having a compile-time error will make it easier to port.

File: src/errors.rs (hunk 1 above)
Comment (vext01) [reply src/errors.rs]: Will it work? The `e`s have different types.

File: src/lib.rs [hunk 3]
```diff
@@ -151,10 +155,31 @@ impl Tracer {
...
+        if unsafe { geteuid() } == 0 {
+            // Root can always trace.
+            return Ok(());
+        }
+
+        let mut f = File::open(&PERF_PERMS_PATH)?;
+        let mut buf = String::new();
+        f.read_to_string(&mut buf)?;
+        let buf = buf.trim();
+        let perm = buf.parse::<i8>()?;
```
Comment (ltratt) [inline src/lib.rs]: What's the use of having `perm` is an intrmediate variable? Wouldn't `if buf.trim().parse::<i8>()? != -1 { return Err(...) }` be simpler?

File: src/lib.rs (hunk 2 above)
Comment (vext01) [reply src/lib.rs]: Shall we just say this doesn't work on !Linux in the README? The whole thing relies on perf. Or put on test at an entry point or something?

File: src/lib.rs (hunk 3 above)
Comment (vext01) [reply src/lib.rs]: Can do, yeah.

File: src/errors.rs (hunk 1 above)
Comment (ltratt) [reply src/errors.rs]: Ah, I hadn't though of that. They probably won't work... but would be interesting to try!

File: src/lib.rs (hunk 2 above)
Comment (vext01) [reply src/lib.rs]: Let's make build.rs crash on !Linux.

Comment (ltratt) [reply src/lib.rs]: From experience of porting, it's *much* better if you make each individual point of likely divergence fail. Just saying "it doesn't work on !Linux" globally doesn't help a porter much.

File: src/errors.rs (hunk 1 above)
Comment (vext01) [reply src/errors.rs]: They all implement `Error`. So maybe...

Comment (ltratt) [reply src/errors.rs]: If `Error` implements the appropriate formatter, it will probably work I think.

File: src/lib.rs (hunk 2 above)
Comment (vext01) [reply src/lib.rs]: OK, but they will be everywhere.

File: src/errors.rs (hunk 1 above)
Comment (vext01) [reply src/errors.rs]: No cigar.

```rust
        match self {    
            &TraceMeError::FFIIntoString(ref e)                           
            | &TraceMeError::FFINul(ref e)                           
            | &TraceMeError::IO(ref e)                                          
            | &TraceMeError::NumParseInt(ref e) => write!(f, "{}", e),    
```

```
error[E0308]: mismatched types
  --> src/errors.rs:48:37
   |
48 |             | &TraceMeError::FFINul(ref e)
   |                                     ^^^^^ expected struct `std::ffi::IntoStringError`, found struct `std::ffi::NulError`
   |
   = note: expected type `&std::ffi::IntoStringError`
              found type `&std::ffi::NulError`

error[E0308]: mismatched types
  --> src/errors.rs:49:33
   |
49 |             | &TraceMeError::IO(ref e)
   |                                 ^^^^^ expected struct `std::ffi::IntoStringError`, found struct `std::io::Error`
   |
   = note: expected type `&std::ffi::IntoStringError`
              found type `&std::io::Error`

error[E0308]: mismatched types
  --> src/errors.rs:50:42
   |
50 |             | &TraceMeError::NumParseInt(ref e) => write!(f, "{}", e),
   |                                          ^^^^^ expected struct `std::ffi::IntoStringError`, found struct `std::num::ParseIntError`
   |
   = note: expected type `&std::ffi::IntoStringError`
              found type `&std::num::ParseIntError`

error: aborting due to 3 previous errors
```

Also tried annotating `e`. You can't do that it seems.

File: src/lib.rs (hunk 2 above)
Comment (vext01) [reply src/lib.rs]: In fact, I'd like to do that as a separate PR, if that's OK?

Comment (ltratt) [reply src/lib.rs]: Well if they end up in too many places, maybe we need to rethink the code layout a bit?

Comment (ltratt) [reply src/lib.rs]: I've no problem with that being a separate PR.

File: src/errors.rs (hunk 1 above)
Comment (ltratt) [reply src/errors.rs]: OK, sorry for the noise!

File: src/lib.rs (hunk 2 above)
Comment (vext01) [reply src/lib.rs]: I think we should ease off the software engineer a little for now, since we have no idea if our ideas will work yet. I'm very keen to move on and it doesn't need to be rock solid just yet. We can introduce platform abstractions later.

Comment (ltratt) [reply src/lib.rs]: Point taken. But keep it in mind: it's really painful to introduce these abstractions to even a moderately sized project. So it might be better to bite the bullet at some point not ridiculously far into the future.

Comment (vext01) [reply src/lib.rs]: #17.

You might be right actually. So I think we would want switchable backends, maybe a Travis backend too, which would somewhat address somewhat #10. Hrm. The perf backend basically consists of all of the current C code, so I'd even be tempted to rename traceme.c to `backend_perf.c` or something.

Let me integrate this into Rustc, then we can come back to this.

**Comment by vext01** [comment]
So I think that's all the comments addressed.

**Comment by ltratt** [comment]
OK, if you squash, I can merge.

**Comment by vext01** [comment]
Squashed.
